name: '🔏 Bun Lock Changes'
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: '🚚 Checkout'
        uses: actions/checkout@v7
      - name: '🔏 Bun Lock Changes'
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
