name: '🧪 Run Tests'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing on Node ${{ matrix.node }}
    steps:
      - name: '🚚 Checkout'
        uses: actions/checkout@v7
      - name: '🔧 Setup Bun'
        uses: oven-sh/setup-bun@v2
      - name: '📦️ Install dependencies'
        run: bun install
      - name: '🧪 Run Unit tests'
        run: bun test
      - name: '⚗️ Run CI test'
        uses: ./
        with:
          path: tests/ci/default/bun.lock
          token: ${{ secrets.GITHUB_TOKEN }}
